name: Deploy LATAM API

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Usa la versi칩n m치s reciente

      - name: Set up Python
        uses: actions/setup-python@v2  # Usa la versi칩n m치s reciente
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt

      - name: Test API
        run: |
          python -m unittest discover -s tests

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

